import bytes from "../../bytes.ts";

export const LF = bytes("\n"); // ^J - Enter on Linux
export const CR = bytes("\r"); // ^M - Enter on macOS and Windows (CRLF)
export const TAB = bytes("\t"); // ^I - Tab
export const BS = bytes("\b"); // ^H - Backspace on Linux and Windows
export const DEL = bytes([0x7f]); // ^? - Backspace on macOS
export const ESC = bytes([0x1b]); // ^[ - Escape
export const CANCEL = bytes([0x03]); // ^C - Cancel
export const START = bytes([0x01]); // ^A - Start of text
export const END = bytes([0x05]); // ^E - End of text
export const CLR = bytes("\r\u001b[K"); // Clear the current line
export const CLR_RIGHT = bytes("\u001b[0K");
export const CLR_LEFT = bytes("\u001b[1K");
export const LEFT = bytes("\u001b[D");
export const RIGHT = bytes("\u001b[C");
export const UP = bytes("\u001b[A");
export const DOWN = bytes("\u001b[B");

export const EMOJI_RE = /^(?:\p{Emoji_Modifier_Base}\p{Emoji_Modifier}?|\p{Emoji_Presentation}|\p{Emoji}\uFE0F)(?:\u200d(?:\p{Emoji_Modifier_Base}\p{Emoji_Modifier}?|\p{Emoji_Presentation}|\p{Emoji}\uFE0F))*$/u;

export const UTIMap: { [id: string]: string[]; } = {
    "public.item": ["*/*"],
    "public.audio": ["audio/*"],
    "public.image": ["image/*"],
    "public.text": ["text/*"],
    "public.movie": ["video/*"],
    "public.plain-text": [".txt", "text/plain"],
    "public.rtf": [".rtf", "text/rtf"],
    "public.html": [".html", ".htm", "text/html"],
    "public.xml": [".xml", "text/xml"],
    "public.json": [".json", "application/json"],
    "public.yaml": [".yaml", ".yml", "application/yaml", "application/x-yaml"],
    "public.toml": [".toml", "application/toml"],
    "public.ini": [".ini", "text/ini"],
    "public.comma-separated-values-text": [".csv", "text/csv"],
    "public.c-source": [".c", "text/x-csrc"],
    "public.objective-c-source": [".m", "text/x-objcsrc"],
    "public.c-plus-plus-source": [".cpp", ".cc", ".cp", ".c++", ".cxx", "text/x-c++src"],
    "public.objective-c-plus-​plus-source": [".mm", "text/x-objcppsrc"],
    "public.c-header": [".h", "text/x-chdr"],
    "public.c-plus-plus-header": [".hpp", ".hh", ".h++", ".hxx", "text/x-c++hdr"],
    "com.sun.java-source": [".java", ".jav", "text/x-java-source"],
    "public.assembly-source": [".s", ".S", "text/x-asm"],
    "com.apple.rez-source": [".r", "text/x-rez"],
    "public.mig-source": [".defs", "text/x-mig"],
    "com.apple.symbol-export": [".exp", "text/x-export"],
    "com.netscape.javascript-​source": [".js", ".mjs", ".cjs", "application/javascript", "text/javascript"],
    "public.shell-script": [".sh", ".command", "text/x-shellscript"],
    "public.csh-script": [".csh", "text/x-csh"],
    "public.perl-script": [".pl", ".pm", "application/perl", "text/x-perl", "text/x-perl-script"],
    "public.python-script": [".py", ".pyc", "application/python", "text/x-python", "text/x-python-script"],
    "public.ruby-script": [".rb", "application/ruby", "text/ruby", "text/x-ruby-script"],
    "public.php-script": [".php", ".php3", ".php4", ".php5", ".phtml", "application/php", "text/php", "text/x-php-script"],
    "com.sun.java-web-start": [".jnlp", "application/jnlp"],
    "com.apple.applescript.text": [".applescript"],
    "com.apple.applescript.​script": [".scpt"],
    "public.object-code": [".o"],
    "com.microsoft.windows-​executable": [".exe", ".com", ".bat", ".msi", "application/x-msdownload"],
    "com.microsoft.windows-​dynamic-link-library": [".dll", ".ocx", "application/x-msdownload"],
    "com.sun.java-class": [".class"],
    "com.sun.java-archive": [".jar", "application/java-archive"],
    "com.apple.quartz-​composer-composition": [".qtz", "application/x-quartzcomposer"],
    "org.gnu.gnu-tar-archive": [".gtar", "application/x-gtar"],
    "public.tar-archive": [".tar", "application/x-tar", "application/tar"],
    "org.gnu.gnu-zip-archive": [".gz", ".gzip", "application/x-gzip", "application/gzip"],
    "org.gnu.gnu-zip-tar-archive": [".tgz", "application/x-tar-gz", "application/x-gzip-compressed-tar"],
    "com.apple.binhex-archive": [".hqx", "application/mac-binhex40", "application/binhex"],
    "com.apple.macbinary-​archive": [".bin", "application/x-macbinary", "application/macbinary"],
    "public.vcard": [".vcf", "text/vcard"],
    "public.jpeg": [".jpg", ".jpeg", "image/jpeg"],
    "public.jpeg-2000": [".jp2", "image/jp2"],
    "public.tiff": [".tiff", ".tif", "image/tiff"],
    "com.apple.pict": [".pct", "image/pict"],
    "com.apple.macpaint-image": [".pntg", "image/x-macpaint"],
    "public.png": [".png", "image/png"],
    "public.xbitmap-image": [".xbm", "image/x-xbitmap"],
    "com.apple.quicktime-image": [".qtif", "image/x-quicktime"],
    "com.apple.icns": [".icns", "image/icns"],
    "com.apple.quicktime-movie": [".mov", ".qt", "video/quicktime"],
    "public.avi": [".avi", "video/x-msvideo"],
    "public.mpeg": [".mpg", ".mpeg", "video/mpeg"],
    "public.mpeg-4": [".mp4", "video/mp4"],
    "public.3gpp": [".3gp", "video/3gpp"],
    "public.3gpp2": [".3g2", "video/3gpp2"],
    "public.mp3": [".mp3", "audio/mpeg", "audio/mp3"],
    "public.mpeg-4-audio": [".m4a", "audio/x-m4a"],
    "com.apple.protected-​mpeg-4-audio": [".m4p", "audio/mp4", "audio/x-m4p"],
    "public.ulaw-audio": [".au", "audio/basic"],
    "public.aifc-audio": [".aifc", "audio/x-aifc"],
    "public.aiff-audio": [".aiff", ".aif", "audio/aiff"],
    "com.apple.coreaudio-​format": [".caf", "audio/x-caf"],
    "com.apple.bundle": [".bundle"],
    "com.apple.application-​bundle": [".app"],
    "com.apple.plugin": [".plugin"],
    "com.apple.metadata-​importer": [".mdimporter"],
    "com.apple.dashboard-​widget": [".wdgt"],
    "public.cpio-archive": [".cpio", "application/x-cpio"],
    "com.pkware.zip-archive": [".zip", "application/zip"],
    "com.apple.framework": [".framework"],
    "com.apple.rtfd": [".rtfd", "application/rtfd"],
    "public.opentype-font": [".otf", "application/x-font-opentype"],
    "public.truetype-ttf-font": [".ttf", "application/x-font-truetype"],
    "public.truetype-collection-​font": [".ttc", "application/x-font-ttf"],
    "com.apple.font-suitcase": [".dfont", "application/x-font-suitcase"],
    "com.adobe.postscript-pfb-​font": [".pfb", "application/x-font-type1"],
    "com.adobe.postscript.pfa-​font": [".pfa", "application/x-font-type1"],
    "com.apple.colorsync-profile": [".icc", ".icm", "application/vnd.iccprofile"],
    "com.adobe.pdf": [".pdf", "application/pdf"],
    "com.adobe.postscript": [".ps", "application/postscript"],
    "com.adobe.encapsulated-​postscript": [".eps", "application/postscript"],
    "com.adobe.photoshop-​image": [".psd", "image/vnd.adobe.photoshop", "image/psd"],
    "com.adobe.illustrator.ai-​image": [".ai", "application/illustrator", "application/vnd.adobe.illustrator"],
    "com.compuserve.gif": [".gif", "image/gif"],
    "com.microsoft.bmp": [".bmp", "image/bmp"],
    "com.microsoft.ico": [".ico", "image/x-icon"],
    "com.microsoft.word.doc": [".doc", "application/msword"],
    "com.microsoft.excel.xls": [".xls", "application/vnd.ms-excel"],
    "com.microsoft.powerpoint.​ppt": [".ppt", "application/vnd.ms-powerpoint"],
    "com.microsoft.waveform-​audio": [".wav", "audio/wav"],
    "com.microsoft.advanced-​systems-format": [".asf", "video/x-ms-asf"],
    "com.microsoft.windows-​media-wm": [".wm", "video/x-ms-wm"],
    "com.microsoft.windows-​media-wmv": [".wmv", "video/x-ms-wmv"],
    "com.microsoft.windows-​media-wmp": [".wmp", "video/x-ms-wmp"],
    "com.microsoft.windows-​media-wma": [".wma", "audio/x-ms-wma"],
    "com.microsoft.advanced-​stream-redirector": [".asx", "video/x-ms-asx"],
    "com.microsoft.windows-​media-wmx": [".wmx", "video/x-ms-wmx"],
    "com.microsoft.windows-​media-wvx": [".wvx", "video/x-ms-wvx"],
    "com.microsoft.windows-​media-wax": [".wax", "audio/x-ms-wax"],
    "com.apple.iwork.pages.sffpages": [".pages", "application/x-iwork-pages-sffpages"],
    "com.apple.iwork.numbers.sffnumbers": [".numbers", "application/x-iwork-numbers-sffnumbers"],
    "com.apple.iwork.keynote.sffkey": [".key", "application/x-iwork-keynote-sffkey"],
    "com.truevision.tga-image": [".tga", "image/x-tga"],
    "com.sgi.sgi-image": [".sgi", "image/sgi"],
    "com.sgi.rgb-image": [".rgb", "image/x-rgb"],
    "com.ilm.openexr-image": [".exr", "image/x-exr"],
    "com.kodak.flashpix.image": [".fpx", ".fpix", "image/vnd.fpx"],
    "com.j2.jfx-fax": [".jfx", "image/jfax"],
    "com.js.efx-fax": [".efx", "image/efax"],
    "com.digidesign.sd2-audio": [".sd2", "audio/x-sd2"],
    "com.real.realmedia": [".rm", "application/vnd.rn-realmedia"],
    "com.real.realmedia-vbr": [".rv", ".rmvb", "application/vnd.rn-realmedia-vbr"],
    "com.real.realaudio": [".ra", "audio/vnd.rn-realaudio"],
    "com.real.smil": [".smil", "application/smil"],
    "com.allume.stuffit-archive": [".sit", "application/x-stuffit"],
    "org.opml.opml": [".opml", "text/x-opml"],
    "net.daringfireball.markdown": [".md", "text/markdown"],
    "vnd.sqlite3": [".sqlite3", ".sqlite", ".db", "application/x-sqlite3"],
    "public.iso-image": [".iso", "application/x-iso-image"],
    "com.apple.disk-image": [".dmg", "application/x-apple-diskimage"],
    "public.heic": [".heic", ".heif", "image/heic"],
    "org.openxmlformats.spreadsheetml.sheet": [".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"],
    "org.openxmlformats.presentationml.presentation": [".pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation"],
    "org.openxmlformats.wordprocessingml.document": [".docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"],
    "com.apple.installer-package-archive": [".pkg", "application/x-apple-installer-package"],
    "public.mpeg-2-transport-stream": [".ts", "video/mp2t", "application/typescript", "text/typescript"],
    "public.x509-certificate": [".cer", ".crt", ".der", "application/x-x509-ca-cert"],
    "com.rsa.pkcs-12": [".p12", ".pfx", "application/x-pkcs12"],
};
