import "./string/augment";
import "./number/augment";
import "./array/augment";
import "./uint8array/augment";
import "./object/augment";
import "./math/augment";
import "./promise/augment";
import "./collections/augment";
import "./error/augment";
