name: Bun CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21.x
          cache: 'npm'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - run: npm i
      - run: bun run test:bun
