name: Publish
on:
  release:
    types: [created]

jobs:
  test-node:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5 
        with:
          python-version: '3.11' 
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm i
      - run: npm run test

  test-tsx:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5 
        with:
          python-version: '3.11' 
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm i
      - run: npm run test:tsx

  test-bun:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21.x
          cache: 'npm'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - run: npm i
      - run: npm run test:bun

  test-deno:
    runs-on: ${{ matrix.runner }}

    strategy:
      matrix:
        runner: [ ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x

      - run: deno run -A test-deno.ts

  test-jsdom:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21.x
          cache: 'npm'

      - run: npm i
      - run: npm i -D jsdom
      - run: npm run test:jsdom

  test-pty:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5 
        with:
          python-version: '3.11' 
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Setup Deno
        # uses: denoland/setup-deno@v1
        uses: denoland/setup-deno@61fe2df320078202e33d7d5ad347e7dcfa0e8f31  # v1.1.2
        with:
          deno-version: v1.x
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
      - run: npm i
      - run: npm i -D node-pty
      - run: npm run test:pty

  test-windows:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm i
      - run: npm run test:tsx

  publish-npm:
    needs: [test-node, test-tsx, test-bun, test-deno, test-jsdom, test-pty, test-windows]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21.x
          cache: 'npm'
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

  publish-jsr:
    needs: [test-node, test-tsx, test-bun, test-deno, test-jsdom, test-pty, test-windows]
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 21.x
          cache: 'npm'

      - name: Install Dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Publish to JSR
        run: npx jsr publish
